//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyMarket.Exceptions.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResourceMessageException {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceMessageException() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MyMarket.Exceptions.Resources.ResourceMessageException", typeof(ResourceMessageException).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown error..
        /// </summary>
        public static string GENERIC_UNKNOWN_ERROR {
            get {
                return ResourceManager.GetString("GENERIC_UNKNOWN_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Barcode must be 12 or 13 digits..
        /// </summary>
        public static string PRODUCT_BARCODE_INVALID_FORMAT {
            get {
                return ResourceManager.GetString("PRODUCT_BARCODE_INVALID_FORMAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product barcode is required..
        /// </summary>
        public static string PRODUCT_BARCODE_REQUIRED {
            get {
                return ResourceManager.GetString("PRODUCT_BARCODE_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product category is required..
        /// </summary>
        public static string PRODUCT_CATEGORY_REQUIRED {
            get {
                return ResourceManager.GetString("PRODUCT_CATEGORY_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product description must not exceed 500 characters..
        /// </summary>
        public static string PRODUCT_DESCRIPTION_MAX_LENGTH {
            get {
                return ResourceManager.GetString("PRODUCT_DESCRIPTION_MAX_LENGTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product name must not exceed 100 characters..
        /// </summary>
        public static string PRODUCT_NAME_MAX_LENGTH {
            get {
                return ResourceManager.GetString("PRODUCT_NAME_MAX_LENGTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product name is required..
        /// </summary>
        public static string PRODUCT_NAME_REQUIRED {
            get {
                return ResourceManager.GetString("PRODUCT_NAME_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price must be greater than zero..
        /// </summary>
        public static string PRODUCT_PRICE_INVALID {
            get {
                return ResourceManager.GetString("PRODUCT_PRICE_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stock quantity cannot be negative..
        /// </summary>
        public static string PRODUCT_STOCK_QUANTITY_INVALID {
            get {
                return ResourceManager.GetString("PRODUCT_STOCK_QUANTITY_INVALID", resourceCulture);
            }
        }
    }
}
